name: Node CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, windows-2016, macOS-latest, ubuntu-latest]
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: INSTALL
              run: npm install
              env:
                  CI: true
            - name: BUILD
              run: npm run build --if-present
            - name: TEST
              run: npm test
